name: test-downstream-merge
run-name: test-downstream-merge-${{ github.ref_name }}-${{ github.sha }} 
on: push

jobs:
  tester:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Tester
        run: |
          echo ${{ github.event.organization }}
