name: tester
run-name: tester

on:
  workflow_dispatch:
    inputs:
      file: 
        required: false
        type: string
        default: ""
      context: 
        required: false
        type: string
        default: "."


jobs:
  tester:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Dockerfile name and location
        run: echo "dockerfile=${{ inputs.file != '' && inputs.file || format('{0}/Dockerfile', inputs.context) }}" >> ${GITHUB_OUTPUT}
        id: get-dockerfile
      - name: echo Dockerfile name
        run: echo ${{ steps.get-dockerfile.outputs.dockerfile }}
