name: tester
run-name: tester
on: push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  tester:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}   
    steps: 
      -
        name: Tester
        run: |
          echo ${{ github.event}}
          echo "${GITHUB_CONTEXT}"
          gh api orgs/grafana/memberships/ricky-undeadcoders
