name: tester
run-name: tester

on:
  workflow_dispatch:
    inputs:
      repo: 
        required: true
        type: string
        default: ""


jobs:
  tester:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repo name
        run: echo "repo_name=${{ inputs.repo != '' && inputs.repo || 'ricky-undeadcoders/repo' }}" >> ${GITHUB_OUTPUT}
        id: get-repo-name
      - name: echo repo name
        run: echo ${{ steps.get-repo-name.outputs.repo_name }}
          # - name: "Checkout src repo"
          #   uses: actions/checkout@v4
          #   with: 
          #     repository: ${{ steps.get-repo-name.outputs.repo_name }}
          #     ref: ${{ inputs.ref }}
          #     path: src
          #     fetch-depth: 0
