name: tester
run-name: tester

on: push

env:
  REF: main

jobs:
  tester:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Set branch name
        working-directory: repo
        run: |
          BRANCH_NAME=${REF}-$(git log -1 --format=%H)
          git checkout -b $BRANCH_NAME
          touch TestFile.txt
          git add -A; git status;
          git log;
