name: trigger-downstream-mirror
run-name: trigger-mirror-${{ github.ref_name }}-${{ github.sha }} 
on:
  pull_request_target:
    types:
      - opened
    branches:
      - "main"
      - "v*"

env:
  GH_TOKEN: ${{ secrets.PA_TOKEN }}

jobs:
  test-for-downstream-merge-conflicts:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Check for mirror conflicts "${GITHUB.REF_NAME}" "${GITHUB_SHA:0:8}"  
        run: |
          gh workflow run check-pr-for-conflicts.yml \
          -f ref=${GITHUB_REF_NAME} \
          -f commit=${GITHUB_SHA} \
          --repo ricky-undeadcoders/grafana-delivery-pipelines/

