name: tester
run-name: tester
on: push

jobs:
  tester:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Tester
        run: |
          echo ${{ github.event}}
          echo ${{ toJson(github) }}
