name: trigger-mirror
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  # pull_request_target:
  #   types:
  #     - closed
  #   branches:
  #     - "main"
  push:
    branches:
      - "main"
jobs:
  trigger-downstream-mirror-branch:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PA_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ricky-undeadcoders/grafana-delivery-pipelines/dispatches \
            -d '{"event_type":"mirror-branch","client_payload":{"ref":"${{ github.ref }}","repo": "${{ github.repository }}" }'
