name: trigger-downstream-mirror
run-name: trigger-mirror-${{ github.ref_name }}-${{ github.sha }} 
on:
  pull_request_target:
    types:
      - closed
    branches:
      - "main"
      - "v*"

env:
  GH_TOKEN: ${{ secrets.PA_TOKEN }}

jobs:
  trigger-downstream-mirror:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - 
        name: Trigger downstream mirror "${{ github.ref_name }}" "${{ github.sha }}"  
        run: |
          gh workflow run mirror-branch.yml \
          -f ref=${GIHUB_REF_NAME} \
          -f sha=${GITHUB_SHA} \
          --repo ricky-undeadcoders/grafana-delivery-pipelines
          
